# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
# -   repo: https://github.com/pycqa/isort
#     rev: 5.10.1
#     hooks:
#       - id: isort
#         name: isort (python)
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        language_version: python3.10
        exclude: ^legacy/
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: flake8
        exclude: ^legacy/
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.931'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        exclude: ^legacy/
        